"""Prototype catalogue: requires HSE approval before operational use."""
VERSION = "prototype-catalogue-2"
FAMILIES = [{'id': 'P-001',
  'activity': 'Mechanical Lifting',
  'hazard': 'Suspended Load',
  'activity_re': '\\b(?:crane lifting activity|lifting operations?|lifting activity|lifting|crane '
                 'radius|hoist(?:ed|ing)?|rigging)\\b',
  'hazard_re': '\\b(?:suspended (?:pipe|load|steel|equipment|pump|unit)|lifting zone|crane radius|below '
               '(?:the )?load|(?:hung|hanging|suspended|dangling|held aloft) (?:from|by|on) (?:an? |the '
               ')?(?:mobile |overhead )?(?:crane|hoist)|(?:pump|load|unit|equipment|pipe) (?:being '
               ')?(?:hoisted|lifted))\\b',
  'equipment_re': '\\b(crane|suspended pipe|sling|hoist)\\b',
  'exposure_re': '\\b(?:standing beneath|worker beneath|walked beneath|entered (?:the '
                 ')?(?:lifting|exclusion) zone|inside (?:the )?lifting zone|crossed below|under (?:the '
                 ')?suspended load|entered crane '
                 'radius|(?:walk(?:ed|ing)?|stood|standing|was|were|is|remained|working) (?:directly '
                 ')?(?:under|beneath|below) (?:an? |the )?(?:(?:\\d+(?:\\.\\d+)?[- '
                 '](?:tonne|ton|kg)|suspended|hanging|hoisted) )?(?:load|pipe|pump|unit|equipment))\\b',
  'barrier': 'Exclusion Zone / Access Control',
  'barrier_re': '\\b(?:exclusion (?:zone|barrier|barricade)|barricade|access control|lifting '
                '(?:zone|area)|work area|cordon(?:ed)?(?: off)?|restricted (?:area|zone))\\b',
  'threat': 'Dropped or swinging load',
  'consequence': 'Fatal struck-by / crushing injury',
  'rules': ['Line of Fire', 'Safe Mechanical Lifting']},
 {'id': 'P-002',
  'activity': 'Energy Isolation',
  'hazard': 'Unexpected Energisation',
  'activity_re': '\\b(maintenance|repair|energy isolation|lockout|loto)\\b',
  'hazard_re': '\\b(energised|energized|unexpected start|live circuit|rotating shaft|residual '
               'pressure|lockout|loto)\\b',
  'equipment_re': '\\b(pump|motor|switchgear|circuit|rotating shaft)\\b',
  'exposure_re': '\\b(worker (?:touching|repairing)|hands? inside|technician working|contact with '
                 'live|maintenance on)\\b',
  'barrier': 'Lockout / Tagout',
  'barrier_re': '\\b(lockout|loto|isolation|tagout)\\b',
  'threat': 'Unexpected release of hazardous energy',
  'consequence': 'Fatal electrocution / entanglement',
  'rules': ['Energy Isolation', 'Line of Fire']},
 {'id': 'P-003',
  'activity': 'Process Pressure',
  'hazard': 'Process Overpressure',
  'activity_re': '\\b(during operation|process operation|pressure testing|pressurised|pressurized)\\b',
  'hazard_re': '\\b(pressure safety valve|psv|overpressure|pressure relief valve)\\b',
  'equipment_re': '\\b(pressure safety valve|psv|pressure relief valve|vessel|separator)\\b',
  'exposure_re': '\\b(worker nearby|personnel near|operator beside)\\b',
  'barrier': 'Pressure Safety Valve',
  'barrier_re': '\\b(pressure safety valve|psv|pressure relief valve)\\b',
  'threat': 'Process Overpressure',
  'consequence': 'Fatal rupture / blast injury',
  'rules': ['Bypassing Safety Controls']},
 {'id': 'P-004',
  'activity': 'Excavation',
  'hazard': 'Underground Pipeline / Line Strike',
  'activity_re': '\\b(excavation(?: work)?|digging|trenching)\\b',
  'hazard_re': '\\b(pipeline route|buried pipeline|underground (?:line|pipeline)|marked pipeline)\\b',
  'equipment_re': '\\b(pipeline|excavator|backhoe)\\b',
  'exposure_re': '\\b(close to|near (?:a |the )?pipeline|within \\d+ (?:m|metres))\\b',
  'barrier': 'Permit / Underground Line Verification',
  'barrier_re': '\\b(permit(?: details)?|underground line verification|line verification)\\b',
  'threat': 'Live pipeline strike',
  'consequence': 'Fatal fire / explosion',
  'rules': ['Work Authorisation', 'Line of Fire']},
 {'id': 'P-005',
  'activity': 'Hot Work',
  'hazard': 'Ignition of Flammable Atmosphere',
  'activity_re': '\\b(hot work|welding|grinding|cutting torch)\\b',
  'hazard_re': '\\b(flammable (?:gas|vapou?r)|hydrocarbon leak|gas release|welding)\\b',
  'equipment_re': '\\b(welding set|torch|tank|grinder)\\b',
  'exposure_re': '\\b(worker welding|welder inside|welding near|grinding near)\\b',
  'barrier': 'Gas Test / Hot Work Permit',
  'barrier_re': '\\b(gas test|hot work permit|fire watch)\\b',
  'threat': 'Ignition',
  'consequence': 'Fatal burns / explosion',
  'rules': ['Hot Work', 'Work Authorisation']},
 {'id': 'P-006',
  'activity': 'Working at Height',
  'hazard': 'Fall from Height',
  'activity_re': '\\b(working at height|scaffold(?:ing)?|roof work|ladder work)\\b',
  'hazard_re': '\\b(unprotected edge|open edge|scaffold|roof|height of)\\b',
  'equipment_re': '\\b(scaffold|ladder|platform|roof)\\b',
  'exposure_re': '\\b(worker (?:at|on)|standing on|working near (?:an? )?(?:open|unprotected) edge)\\b',
  'barrier': 'Fall Protection',
  'barrier_re': '\\b(harness|guardrail|fall protection|lifeline)\\b',
  'threat': 'Loss of balance / unprotected edge',
  'consequence': 'Fatal fall',
  'rules': ['Working at Height']},
 {'id': 'P-007',
  'activity': 'Gas Detection',
  'hazard': 'Toxic Gas / H2S',
  'activity_re': '\\b(gas testing|gas detection|h2s monitoring)\\b',
  'hazard_re': '\\b(h2s|hydrogen sulphi?de|toxic gas)\\b',
  'equipment_re': '\\b(gas detector|gas monitor|detector)\\b',
  'exposure_re': '\\b(worker exposed|inhaled|personnel exposed|entered gas cloud)\\b',
  'barrier': 'Gas Detector',
  'barrier_re': '\\b(gas detector|gas monitor|detector)\\b',
  'threat': 'Toxic gas exposure',
  'consequence': 'Fatal poisoning / asphyxiation',
  'rules': ['Line of Fire']},
 {'id': 'P-008',
  'activity': 'Confined Space',
  'hazard': 'Oxygen Deficiency',
  'activity_re': '\\b(confined space|vessel entry|tank entry)\\b',
  'hazard_re': '\\b(oxygen deficien(?:t|cy)|confined space|tank entry)\\b',
  'equipment_re': '\\b(tank|vessel|pit)\\b',
  'exposure_re': '\\b(worker entered|person inside|entered (?:the )?tank)\\b',
  'barrier': 'Entry Permit / Atmosphere Test',
  'barrier_re': '\\b(entry permit|atmosphere test|gas test)\\b',
  'threat': 'Unsafe atmosphere',
  'consequence': 'Fatal asphyxiation',
  'rules': ['Confined Space', 'Work Authorisation']},
 {'id': 'P-009',
  'activity': 'Driving',
  'hazard': 'Vehicle Collision',
  'activity_re': '\\b(driving|vehicle movement|reversing)\\b',
  'hazard_re': '\\b(?:speeding|reversing vehicle|vehicle collision|vehicle impact|uncontrolled vehicle)\\b',
  'equipment_re': '\\b(truck|vehicle|tanker)\\b',
  'exposure_re': '\\b(pedestrian behind|worker behind|driver speeding)\\b',
  'barrier': 'Vehicle / Pedestrian Separation',
  'barrier_re': '\\b(spotter|seat ?belt|pedestrian barrier|segregation)\\b',
  'threat': 'Vehicle impact',
  'consequence': 'Fatal collision',
  'rules': ['Driving', 'Line of Fire']},
 {'id': 'P-010',
  'activity': 'Well Control',
  'hazard': 'Uncontrolled Well Pressure',
  'activity_re': '\\b(well control|drilling|well intervention)\\b',
  'hazard_re': '\\b(well kick|blowout|well pressure)\\b',
  'equipment_re': '\\b(bop|blowout preventer|well)\\b',
  'exposure_re': '\\b(crew on rig|worker on rig)\\b',
  'barrier': 'Blowout Preventer',
  'barrier_re': '\\b(bop|blowout preventer)\\b',
  'threat': 'Loss of well control',
  'consequence': 'Fatal fire / explosion',
  'rules': ['Bypassing Safety Controls', 'Line of Fire']}]
