# Generated by Django 5.2.17 on 2026-09-08 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=80, unique=True)),
                ('source_record_id', models.CharField(max_length=120)),
                ('source_system', models.CharField(default='MANUAL_ENTRY', max_length=120)),
                ('schema_version', models.CharField(default='canonical-1', max_length=40)),
                ('source_hash', models.CharField(max_length=64)),
                ('context', models.JSONField(default=dict)),
                ('site', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('report_type', models.CharField(max_length=30)),
                ('event_timestamp', models.DateTimeField(db_index=True)),
                ('description', models.TextField()),
                ('immediate_action', models.TextField(blank=True)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_record_id'), name='unique_source_record')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('sif_label', models.CharField(db_index=True, max_length=30)),
                ('priority', models.CharField(db_index=True, max_length=20)),
                ('model_version', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='core.report')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=20)),
                ('review_reason', models.JSONField(default=list)),
                ('status', models.CharField(default='OPEN', max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.analysis')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='core.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=40)),
                ('reviewer', models.CharField(max_length=120)),
                ('identity_verified', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('ai_recommendation', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='core.reviewitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
